### ISSUE TITLE
Crash when loading with WeatherManager Enabled

### ISSUE THREAD

**Issue by SkySom** [Terasology/WeatherManager#4]
Appears that WeatherManager may be broken with newer versions of Terasology. See https://github.com/MovingBlocks/Terasology/issues/2335

**Comment by Cervator** [comment]
Fixed in https://github.com/Terasology/WeatherManager/commit/fd8b96f6a2e86ea682ec8a06535031c1215c4d9f - going to go back to engine to submit a question about why `@In` doesn't work yet direct CoreRegistry usage does :-)
